### ISSUE TITLE
Dockerize PCL Dev Environment

### ISSUE THREAD

**Issue by li-rongcheng** [RedwoodTEQ/Point-Cloud-Modelling#8]

**Comment by birdinforest** [comment]
Commit docker file.
Pushing image to docker hub.

To-do:
+ X11 forwarding (win, mac, ubuntu)
+ A additional example pcl project that don't need visualization.

**Comment by birdinforest** [comment]
I find that we'd better to build image by one base image and multiple libraries images, finally build the dev image by multi-stage image building.
ref: https://github.com/RedwoodTEQ/Point-Cloud-Modelling/issues/17
